### PR TITLE
Additional styling and content for Death in Space system.

### PR DESCRIPTION
**Pull request by mcglincy**
hi John - I have several open questions wrt how best to handle the things I'm doing on this PR. Note: I am new to Tailwind.

- What is the best way to handle styling all h1, h2, and tw-button for the Death in Space site? I'm currently twiddling them directlhy in deathinspace.css, which seems incorrect for Tailwind (is it?).

- Is there any trick to getting tw-uppercase working? (Neither tw-uppercase or uppercase classes seemed to be working for me.) Currently I have explicit style= attributes set to accomplish this, which again seems Tailwind-incorrect.

- What's the best way to handle different About page html content? Right now I have a Death in Space specific erb that references a different field in en.yml, which feels a bit hacky.

### CODE REVIEW

**Comment by jdbann** [comment]
> * What is the best way to handle styling all h1, h2, and tw-button for the Death in Space site? I'm currently twiddling them directlhy in deathinspace.css, which seems incorrect for Tailwind (is it?).

I'm aiming to have a separate Tailwind config and CSS file for each theme (with a common preset full of standard config and base styling). This was a pain until recently (https://tailwindcss.com/blog/tailwindcss-v3-2#multiple-config-files-in-one-project-using-config) but now it's just about finding the time to set that up properly. It would mean we could escape the CSS variables workaround and then you'd have a natural place to freely style elements however you fancy.

Long term, I want to extract all the Tailwind classes into ones specifically defined for the components (something like `.entry-tile` and sub-elements like `.entry-tile__wrapper`). Then in the theme's CSS file it could be modified freely with:

```css
@layer components {
  .entry-tile {
    @apply bg-scary-red p-8 hover:bg-even-scarier-red;
  }
}
```

But for now keeping them in `deathinspace.css` is the best way.

> * Is there any trick to getting tw-uppercase working? (Neither tw-uppercase or uppercase classes seemed to be working for me.) Currently I have explicit style= attributes set to accomplish this, which again seems Tailwind-incorrect.

Check that you're running `bin/dev` - this runs the JS and CSS builders in watch mode. As Tailwind only generates the classes that are in use, it might be that it built them before you added the `.tw-uppercase` class.

> * What's the best way to handle different About page html content? Right now I have a Death in Space specific erb that references a different field in en.yml, which feels a bit hacky.

I left some options in #762 but also looks like a good option

**Comment by mcglincy** [comment]
You were right - I've been using puma-dev to run the server locally instead of ./bin/dev, so wasn't running all the stuff in Procfile.dev. tw-uppercase now works fine.

I left my about.html+deathinspace.erb solution in place on this PR, and I'll comment on #762 wrt other possible solutions.

Thanks for the help and explanations. Learning tailwind is interesting :)

**Comment by mcglincy** [comment]
btw I think this PR is ready to be merged, assuming it looks good to you. Thanks!

**Review by jdbann — APPROVED** [review]
Code looks great. Haven't tested I'm afraid but I trust you on this and will be responsive on any fixes

**Comment by jdbann** [comment]
Sorry I've slept on this! I'll get it merged and deployed now

**Pull request merged**
